/** @type {import('tailwindcss').Config} */
// Thème "Heritage" — Architectural Minimalism + Journalistic Gravitas.
// Palette unifiée à partir des écrans générés par Stitch (MCP).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // — Noms sémantiques Heritage —
        ink: '#1A1C1E',
        clay: '#B8422E',
        limestone: '#F7F5F2',
        slate: '#6C7278',
        // — Brand / interaction —
        primary: '#972a19',
        'on-primary': '#ffffff',
        'primary-container': '#b8422e',
        'on-primary-container': '#ffe5e0',
        'primary-fixed': '#ffdad3',
        'primary-fixed-dim': '#ffb4a6',
        'on-primary-fixed': '#3f0300',
        'on-primary-fixed-variant': '#881f0f',
        'surface-tint': '#a93724',
        'inverse-primary': '#ffb4a6',
        // — Secondary —
        secondary: '#5d5e61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e5',
        'on-secondary-container': '#636467',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        // — Tertiary —
        tertiary: '#525250',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6a6a68',
        'on-tertiary-container': '#edebe8',
        'tertiary-fixed': '#e4e2df',
        'tertiary-fixed-dim': '#c8c6c4',
        'on-tertiary-fixed': '#1b1c1a',
        'on-tertiary-fixed-variant': '#474745',
        // — Surfaces —
        surface: '#fbf9f6',
        'surface-dim': '#d7dae0',
        'surface-bright': '#fbf9f6',
        'surface-variant': '#e4e2df',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'surface-container-high': '#e5e8ee',
        'surface-container-highest': '#dfe3e8',
        'on-surface': '#181c20',
        'on-surface-variant': '#58413d',
        'inverse-surface': '#2d3135',
        'inverse-on-surface': '#eef1f7',
        // — Outlines —
        outline: '#8b716c',
        'outline-variant': '#dfbfba',
        // — Background —
        background: '#f7f5f2',
        'on-background': '#181c20',
        // — Statut / sémantique —
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        'space-xs': '4px',
        'space-sm': '8px',
        'space-md': '16px',
        'space-lg': '32px',
        'space-xl': '64px',
        gutter: '24px',
        'container-margin': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
        display: ['Public Sans', 'sans-serif'],
        h1: ['Public Sans', 'sans-serif'],
        'headline-xl': ['Public Sans', 'sans-serif'],
        'headline-lg': ['Public Sans', 'sans-serif'],
        'headline-md': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
        'body-sm': ['Public Sans', 'sans-serif'],
        caption: ['Public Sans', 'sans-serif'],
        'label-md': ['Public Sans', 'sans-serif'],
        'label-mono': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        arabic: ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        h1: ['3rem', { lineHeight: '1.1' }],
        'headline-xl': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-mono': ['0.875rem', { lineHeight: '1', fontWeight: '500' }],
        'label-caps': ['0.75rem', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
